name: Build backend app and push to GitHub Packages

defaults:
  run:
    working-directory: "backend/"

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - 'backend/**'

env:
  PACKAGES_KEY ${{ secrets.PACKAGES_KEY }}
  

jobs:
  BuildAndDeploy:
    name: Build backend app and push to GitHub Packages
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Getting dependencies
      run: |
        apt-get update && apt-get -y install maven
    - name: Execute tests
      run: |
        mvn clean test
    - name: Build Java
      run: |
        mvn clean package
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ secrets.PACKAGES_KEY }}

    - name: Build the BACKEND Docker image
      run: |
            docker build . --tag ghcr.io/higorcangirana61/backend-app:latest
            docker push ghcr.io/higorcangirana61/backend-app:latest