name: Build frontend app and push to GitHub Packages

defaults:
  run:
    working-directory: "frontend/"

on:
  workflow_dispatch:
  push:
    branches:
    - main

env:
  PACKAGES_KEY: ${{ secrets.PACKAGES_KEY }}
  

jobs:
  BuildAndDeploy:
    name: Build frontend app and push to GitHub Packages
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Getting dependencies
      run: |
        apt-get update && apt-get -y install npm
        npm install -g @angular/cli
    - name: Execute tests
      run: |
        ng test
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PACKAGES_KEY }}

    - name: Build the FRONTEND Docker image
      run: |
            docker build . --tag ghcr.io/higorcangirana61/frontend-app:latest
            docker push ghcr.io/higorcangirana61/frontend-app:latest
